# src/Ais/StatusKeaktifanBundle/Resources/config/validation.yml
Ais\StatusKeaktifanBundle\Entity\StatusKeaktifan:
    properties:
        status_keaktifan:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 2
                max: 100
                minMessage: "Your title must be at least {{ limit }} characters length"
                maxMessage: "Your title name cannot be longer than {{ limit }} characters length"
