<?php

namespace Ais\StatusKeaktifanBundle\Repository;

/**
 * StatusKeaktifanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusKeaktifanRepository extends \Doctrine\ORM\EntityRepository
{
}
